spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.209.51:3306/graduation_design?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: tjdxdykw.123
  redis:
    host: 43.143.209.51
    port: 6379
    password: tjdxdykw.123
    database: 10
    client-type: jedis
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.209.51:8848
  main:
    allow-bean-definition-overriding: true

server:
  port: 8000

minio:
  endpoint: http://43.143.209.51:9000
  # minio登录用户名
  userName: adminMinio
  # minio登录密码
  password: tjdxdykw.123

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    root: info
