spring:
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brainu_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: brainu
    password: rnZbcCXnhatLA5eS
  redis:
    host: 43.143.20.63
    port: 6389
#    password:
    database: 10
    client-type: jedis
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

server:
  port: 8000
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

minio:
  endpoint: https://brainu.nexuracloud.cn/minio
  user-name: admin
  password: FuYR6sXBxpS9

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    root: info
