server:
  port: 7000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.209.51:3306/graduation_design?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: tjdxdykw.123
  redis:
    host: 43.143.209.51
    port: 6379
    password: tjdxdykw.123
    database: 10
    client-type: jedis
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


